### ISSUE TITLE
一旦接收自定义表情就异常退出

### ISSUE THREAD

**Issue by taoxiyang** [kanjielu/jeeves#10]
步骤：
1、jeeves登录web微信
2、用另外一个账号给使用jeeves登录的微信号发送一个自定义表情
现象：
服务端sync接口秒回，过一两秒返回 -3003 异常

2018-05-05 00:19:30.518  INFO 4886 --- [       Thread-7] c.w.l.goblin.wechat.service.SyncServie   : [SYNCCHECK] retcode = 0, selector = 2
2018-05-05 00:19:30.571  INFO 4886 --- [       Thread-7] c.w.l.goblin.wechat.service.SyncServie   : [SYNCCHECK] retcode = 0, selector = 2
2018-05-05 00:19:30.637  INFO 4886 --- [       Thread-7] c.w.l.goblin.wechat.service.SyncServie   : [SYNCCHECK] retcode = 0, selector = 2
2018-05-05 00:19:30.711  INFO 4886 --- [       Thread-7] c.w.l.goblin.wechat.service.SyncServie   : [SYNCCHECK] retcode = 0, selector = 2
2018-05-05 00:19:30.769  INFO 4886 --- [       Thread-7] c.w.l.goblin.wechat.service.SyncServie   : [SYNCCHECK] retcode = 0, selector = 2
2018-05-05 00:19:30.833  INFO 4886 --- [       Thread-7] c.w.l.goblin.wechat.service.SyncServie   : [SYNCCHECK] retcode = 0, selector = 2
2018-05-05 00:19:30.901  INFO 4886 --- [       Thread-7] c.w.l.goblin.wechat.service.SyncServie   : [SYNCCHECK] retcode = 0, selector = 2
2018-05-05 00:19:30.954  INFO 4886 --- [       Thread-7] c.w.l.goblin.wechat.service.SyncServie   : [SYNCCHECK] retcode = 0, selector = 2
2018-05-05 00:19:31.008  INFO 4886 --- [       Thread-7] c.w.l.goblin.wechat.service.SyncServie   : [SYNCCHECK] retcode = 0, selector = 2
2018-05-05 00:19:31.075  INFO 4886 --- [       Thread-7] c.w.l.goblin.wechat.service.SyncServie   : [SYNCCHECK] retcode = 0, selector = 2
2018-05-05 00:19:31.141  INFO 4886 --- [       Thread-7] c.w.l.goblin.wechat.service.SyncServie   : [SYNCCHECK] retcode = 0, selector = 2
2018-05-05 00:19:31.214  INFO 4886 --- [       Thread-7] c.w.l.goblin.wechat.service.SyncServie   : [SYNCCHECK] retcode = 0, selector = 2
2018-05-05 00:19:31.267  INFO 4886 --- [       Thread-7] c.w.l.goblin.wechat.service.SyncServie   : [SYNCCHECK] retcode = 0, selector = 2
2018-05-05 00:19:31.332  INFO 4886 --- [       Thread-7] c.w.l.goblin.wechat.service.SyncServie   : [SYNCCHECK] retcode = 0, selector = 2
2018-05-05 00:19:31.399  INFO 4886 --- [       Thread-7] c.w.l.goblin.wechat.service.SyncServie   : [SYNCCHECK] retcode = 0, selector = 2
2018-05-05 00:19:31.474  INFO 4886 --- [       Thread-7] c.w.l.goblin.wechat.service.SyncServie   : [SYNCCHECK] retcode = 0, selector = 2
2018-05-05 00:19:31.515 ERROR 4886 --- [       Thread-7] c.w.l.g.wechat.service.WechatSession     : SyncResponse ret = -3003

com.wacai.loan.goblin.wechat.exception.WechatException: SyncResponse ret = -3003
	at com.wacai.loan.goblin.wechat.utils.WechatUtils.checkBaseResponse(WechatUtils.java:12) ~[classes/:na]
	at com.wacai.loan.goblin.wechat.service.SyncServie.sync(SyncServie.java:77) ~[classes/:na]
	at com.wacai.loan.goblin.wechat.service.SyncServie.onNewMessage(SyncServie.java:115) ~[classes/:na]
	at com.wacai.loan.goblin.wechat.service.SyncServie.listen(SyncServie.java:57) ~[classes/:na]
	at com.wacai.loan.goblin.wechat.service.WechatSession.run(WechatSession.java:146) ~[classes/:na]

2018-05-05 00:19:31.516  INFO 4886 --- [       Thread-7] c.w.l.g.wechat.service.WechatSession     : remove uuid : 4agmP67VMw==
Disconnected from the target VM, address: '127.0.0.1:55151', transport: 'socket'

Process finished with exit code 130 (interrupted by signal 2: SIGINT)

**Comment by kanjielu** [comment]
经我本机测试，可以接受自定义表情。打印的信息应该是[SYNCCHECK] retcode = 0, selector = 2
-3003可能是你测试的时候触发了什么微信的探测机制，判定出你有不正常行为。

**Comment by taoxiyang** [comment]
我用您的代码运行了一遍，仍旧出现上述问题，正常心跳连接如果没有收到新消息的话，微信服务端会阻塞7～8秒，但是如果收到自定义表情的话，微信服务端貌似就不会阻塞了，立马返回[SYNCCHECK] retcode = 0, selector = 2,参考上面的打印日志的时间戳，过几秒钟服务端返回-3003异常，貌似收到自定义表情后jeeves与微信服务端的同步就出现异常了

**Comment by as181920** [comment]
也遇到了，有后续处理方案么
