### ISSUE TITLE
Crash when onReceivingPrivateTextMessage.

### ISSUE THREAD

**Issue by yangboz** [kanjielu/jeeves#14]
Error message as follows:
```
2018-05-28 17:28:38.674  INFO 54725 --- [           main] com.cherry.jeeves.service.SyncServie     : [SYNCCHECK] retcode = 0, selector = 2
2018-05-28 17:28:39.025  INFO 54725 --- [           main] com.cherry.jeeves.MessageHandlerImpl     : onReceivingPrivateTextMessage
2018-05-28 17:28:39.026  INFO 54725 --- [           main] com.cherry.jeeves.MessageHandlerImpl     : from: @48e0f8154dba3d0d9be6ad0e0d8c9da92976cb6b914fcbea8023e79620a777f0
2018-05-28 17:28:39.026  INFO 54725 --- [           main] com.cherry.jeeves.MessageHandlerImpl     : to: @@b1ca4441c1936e5d62bf47b1dbfd29a07047164ed86ffcc35c755296bb7e1e2c
2018-05-28 17:28:39.026  INFO 54725 --- [           main] com.cherry.jeeves.MessageHandlerImpl     : content:Testing 
2018-05-28 17:28:41.254  INFO 54725 --- [           main] utoConfigurationReportLoggingInitializer : 

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2018-05-28 17:28:41.285 ERROR 54725 --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:735) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at com.cherry.jeeves.JeevesApplication.main(JeevesApplication.java:18) [classes/:na]
Caused by: com.cherry.jeeves.exception.WechatException: SendMsgResponse ret = 1204
	at com.cherry.jeeves.utils.WechatUtils.checkBaseResponse(WechatUtils.java:12) ~[classes/:na]
	at com.cherry.jeeves.service.WechatHttpService.sendText(WechatHttpService.java:62) ~[classes/:na]
	at com.cherry.jeeves.MessageHandlerImpl.replyMessage(MessageHandlerImpl.java:157) ~[classes/:na]
	at com.cherry.jeeves.MessageHandlerImpl.onReceivingPrivateTextMessage(MessageHandlerImpl.java:63) ~[classes/:na]
	at com.cherry.jeeves.service.SyncServie.onNewMessage(SyncServie.java:128) ~[classes/:na]
	at com.cherry.jeeves.service.SyncServie.listen(SyncServie.java:61) ~[classes/:na]
	at com.cherry.jeeves.service.LoginService.login(LoginService.java:164) ~[classes/:na]
	at com.cherry.jeeves.Jeeves.start(Jeeves.java:25) ~[classes/:na]
	at com.cherry.jeeves.JeevesApplication.lambda$run$1(JeevesApplication.java:27) [classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	... 6 common frames omitted

2018-05-28 17:28:41.289  INFO 54725 --- [           main] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@1e13529a: startup date [Mon May 28 17:26:35 CST 2018]; root of context hierarchy
2018-05-28 17:28:41.295  INFO 54725 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2018-05-28 17:28:41.297  WARN 54725 --- [           main] c.cherry.jeeves.service.CleanupService   : [*] system is being destroyed
2018-05-28 17:28:41.297  WARN 54725 --- [           main] c.cherry.jeeves.service.CleanupService   : [*] logging out
Disconnected from the target VM, address: '127.0.0.1:51108', transport: 'socket'

Process finished with exit code 1

```

Any idea? Thanks.

**Comment by huyunfan** [comment]
我也碰到了同样的问题~ 现在解决了吗
