### ISSUE TITLE
扫描登陆后抛异常

### ISSUE THREAD

**Issue by kioyong** [kanjielu/jeeves#20]
错误日志
```java
2018-11-02 15:31:28.424  INFO 7736 --- [           main] com.cherry.jeeves.service.LoginService   : [2] qrcode completed
2018-11-02 15:31:28.520  INFO 7736 --- [           main] com.cherry.jeeves.service.LoginService   : [3] statReport completed
2018-11-02 15:31:42.329  INFO 7736 --- [           main] com.cherry.jeeves.service.LoginService   : [*] login status = AWAIT_CONFIRMATION
2018-11-02 15:31:46.800  INFO 7736 --- [           main] com.cherry.jeeves.service.LoginService   : [4] login completed
2018-11-02 15:31:47.709  INFO 7736 --- [           main] com.cherry.jeeves.service.LoginService   : [5] redirect login completed
2018-11-02 15:31:47.787  INFO 7736 --- [           main] com.cherry.jeeves.service.LoginService   : [6] redirect completed
2018-11-02 15:31:48.181  INFO 7736 --- [           main] com.cherry.jeeves.service.LoginService   : [7] init completed
2018-11-02 15:31:48.308  INFO 7736 --- [           main] com.cherry.jeeves.service.LoginService   : [8] status notify completed
2018-11-02 15:31:49.420  INFO 7736 --- [           main] com.cherry.jeeves.service.LoginService   : [*] getContactResponse seq = 0
2018-11-02 15:31:49.420  INFO 7736 --- [           main] com.cherry.jeeves.service.LoginService   : [*] getContactResponse memberCount = 50
2018-11-02 15:31:49.433  INFO 7736 --- [           main] com.cherry.jeeves.service.LoginService   : [9] get contact completed
2018-11-02 15:31:49.568  INFO 7736 --- [           main] com.cherry.jeeves.service.LoginService   : [*] batchGetContactResponse count = 1
2018-11-02 15:31:49.568  INFO 7736 --- [           main] com.cherry.jeeves.service.LoginService   : [10] batch get contact completed
2018-11-02 15:31:49.568  INFO 7736 --- [           main] com.cherry.jeeves.service.LoginService   : [*] login process completed
2018-11-02 15:31:49.569  INFO 7736 --- [           main] com.cherry.jeeves.service.LoginService   : [*] start listening
2018-11-02 15:31:49.699  INFO 7736 --- [           main] com.cherry.jeeves.service.SyncServie     : [SYNCCHECK] retcode = 0, selector = 3
2018-11-02 15:31:49.704  INFO 7736 --- [           main] utoConfigurationReportLoggingInitializer : 

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2018-11-02 15:31:49.714 ERROR 7736 --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
    at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:735) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
    at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
    at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:304) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
    at com.cherry.jeeves.JeevesApplication.main(JeevesApplication.java:18) [classes/:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
    at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:527) [spring-boot-maven-plugin-1.5.7.RELEASE.jar:1.5.7.RELEASE]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
Caused by: com.cherry.jeeves.exception.WechatException: syncCheckResponse ret = 0
    at com.cherry.jeeves.service.SyncServie.listen(SyncServie.java:71) ~[classes/:na]
    at com.cherry.jeeves.service.LoginService.login(LoginService.java:164) ~[classes/:na]
    at com.cherry.jeeves.Jeeves.start(Jeeves.java:25) ~[classes/:na]
    at com.cherry.jeeves.JeevesApplication.lambda$run$1(JeevesApplication.java:27) [classes/:na]
    at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
    ... 12 common frames omitted

2018-11-02 15:31:49.715  INFO 7736 --- [           main] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@3d895b49: startup date [Fri Nov 02 15:31:23 CST 2018]; root of context hierarchy
2018-11-02 15:31:49.716  INFO 7736 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2018-11-02 15:31:49.717  WARN 7736 --- [           main] c.cherry.jeeves.service.CleanupService   : [*] system is being destroyed
2018-11-02 15:31:49.717  WARN 7736 --- [           main] c.cherry.jeeves.service.CleanupService   : [*] logging out
[WARNING] 
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:527)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Failed to execute CommandLineRunner
    at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:735)
    at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716)
    at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
    at com.cherry.jeeves.JeevesApplication.main(JeevesApplication.java:18)
    ... 6 more
Caused by: com.cherry.jeeves.exception.WechatException: syncCheckResponse ret = 0
    at com.cherry.jeeves.service.SyncServie.listen(SyncServie.java:71)
    at com.cherry.jeeves.service.LoginService.login(LoginService.java:164)
    at com.cherry.jeeves.Jeeves.start(Jeeves.java:25)
    at com.cherry.jeeves.JeevesApplication.lambda$run$1(JeevesApplication.java:27)
    at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732)
    ... 12 more
```

**Comment by kioyong** [comment]
selector =3 代表什么？ 我看到Selector定义里面没有。。

**Comment by kioyong** [comment]
只出现一次，不能重现，close了
